### ISSUE TITLE
Update project to Microsoft.NETCore.App version 1.0.1 and 1.1.0

### ISSUE THREAD

**Issue by StefH** [StefH/System.AppDomain.Core#1]

**Comment by ghost** [comment]
@StefH Please update

**Comment by ghost** [comment]
Thanks will this work on Microsoft.NETCore.App version 1.1?

**Comment by StefH** [comment]
I'm not sure.

I will also build a 1.1.0 version. Keep watching this thread + nuget.org

**Comment by ghost** [comment]
@StefH  you legend thanks will keep and eye on thread and nuget

**Comment by StefH** [comment]
NuGet 1.0.3 (app version 1.0.0) and NuGet 1.1.0 (app version 1.0.0) should be visible.

**Comment by ghost** [comment]
Thanks @StefH  just having a little problem not sure if this is related to `AppDomain` or just another few things missing from `system` which was depreciated with .NETCORE

Please see code below:
```
private static IEnumerable<ICmdRCommand> FindAllTypesImplementingICmdRCommand()
        {
            var type = typeof(ICmdRCommand);
            return AppDomain.CurrentDomain.GetAssemblies()
                                          .ToList()
                                          .SelectMany(s => s.GetTypes())
                                          .Where(p => type.IsAssignableFrom(p) && !p.IsInterface && !p.IsAbstract)
                                          .Select(c => (ICmdRCommand)Activator.CreateInstance(c));
        }
```

`IsAssignableFrom`, `IsInterface ` and `IsAbstract` is not available available? and AppDomain.CurrentDomain.GetAssemblies() is expecting `Type` `type`

I am trying to migrate the project cmdR to support `.net core` but not having any luck please see class below
https://github.com/theouteredge/cmdR/blob/master/src/cmdR/Extensions/CmdRExtensions.cs#L148
Maybe you can shed some light please.

**Comment by StefH** [comment]
Try adding these:

`"System.Reflection.Emit": "4.3.0" `and `"System.Reflection.TypeExtensions": "4.3.0"`

See example file:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/294ae81c0644c909175c47b99f0b4fbb6c2924f1/src/System.Linq.Dynamic.Core/ExpressionParser.cs#L494

**Comment by ghost** [comment]
@StefH I will look at this when I get home thank you.

**Comment by ghost** [comment]
@StefH Not having any luck would it be alright with you if I can invite you to my private repro to check it out the error I'm having?

**Comment by StefH** [comment]
Just invite me. Maybe I can help.

**Comment by ghost** [comment]
@StefH I have added you to the project the problems is in link below.

https://github.com/di48l069/cmdR/blob/master/src/cmdR/Extensions/CmdRExtensions.cs

**Comment by StefH** [comment]
I made some structural changes to you projects.
The tests run, 13 still fail, take a look at these.

**Comment by ghost** [comment]
@StefH Thank you will take a look soon 👍

**Comment by StefH** [comment]
Any update?

**Comment by StefH** [comment]
@ghost Closing...
